# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Covid-19 Expert Database
email: health@meedan.com
description: >- # this means to ignore newlines until "baseurl:"
  We are a global team of epidemiologists, public health experts, infectious disease researchers and journalists offering critical insights into complex pandemic science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  card:     "summary_large_image"
logo: /images/logo.png
seo:
  type: Organization

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port


# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - pages:
        space: ENV_CONTENTFUL_EDB_SPACE_ID
        access_token: ENV_CONTENTFUL_EDB_ACCESS_TOKEN
        cda_query:
          locale: '*'
          content_type: 'page'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        content_types:
          page: PageMapper
        destination: 'contentful/spaces/'
    - experts:
        space: ENV_CONTENTFUL_EDB_SPACE_ID
        access_token: ENV_CONTENTFUL_EDB_ACCESS_TOKEN
        cda_query:
          locale: '*'
          content_type: 'contributor'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleStories:
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleStories'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - contributors:
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'contributor'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.pages.page'
    template: 'page'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.pages.page'
    template: 'page-fr'
    name: 'slug'
    dir: '/fr'
  - data: 'contentful.spaces.pages.page'
    template: 'page-hi'
    name: 'slug'
    dir: '/hi'
  - data: 'covid19.questions-en'
    template: 'entry'
    name: 'Question'
    dir: '/questions'
  - data: 'covid19.questions-fr'
    template: 'entry-fr'
    name: 'Question'
    dir: '/fr/questions'
    filter: 'Status'
    filter_condition: record['Status'] == 'Published'
  - data: 'covid19.questions-hi'
    template: 'entry-hi'
    name: 'id'
    dir: '/hi/questions'
    filter: 'Status'
    filter_condition: record['Status'] == 'Published'


# Algolia search
algolia:
  application_id: ENV_ALGOLIA_APPLICATION_ID
  index_name: ENV_ALGOLIA_INDEX_NAME
  search_only_api_key: d031b4f0809f3999da155451bffba6db
  nodes_to_index: 'p'
  settings:
    distinct: true
  files_to_exclude:
    - /index.html
    - fr/index.html
    - hi/index.html
    - glossary.html
    - fr/glossary.html
    - hi/glossary.html
    - glossary/**/index.html
    - /fr/glossary/**/index.html
    - /hi/glossary/**/index.html

# Airtable Fetch Configuration
airtable:
  api_key: ENV_AIRTABLE_API_KEY
  tables:
    - name: 'airtable'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'Expert Database (English)'
          view: 'COVID-19 Expert Database (English)'
          target: 'questions-en'
    - name: 'glossary'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'Glossary (English)'
          view: 'Glossary (English)'
          target: 'glossary-en'
    - name: 'airtable'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'DB (French)'
          view: 'COVID-19 Expert Database (French)'
          target: 'questions-fr'
    - name: 'glossary'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'Glossary (French)'
          view: 'Glossary (French)'
          target: 'glossary-fr'
    - name: 'airtable'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'DB (Hindi)'
          view: 'COVID-19 Expert Database (Hindi)'
          target: 'questions-hi'
    - name: 'glossary'
      app_id: ENV_AIRTABLE_APP_ID
      target: 'covid19'
      sheets:
        - name: 'Glossary (Hindi)'
          view: 'Glossary (Hindi)'
          target: 'glossary-hi'
