# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Covid-19 Expert Database
email: health@meedan.com
description: >- # this means to ignore newlines until "baseurl:"
  We are a global team of epidemiologists, public health experts, infectious disease researchers and journalists offering critical insights into complex pandemic science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  card:     "summary_large_image"
logo: /images/logo.png
seo:
  type: Organization

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port


# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - pages:
        space: ENV_CONTENTFUL_EDB_SPACE_ID
        access_token: ENV_CONTENTFUL_EDB_ACCESS_TOKEN
        cda_query:
          locale: '*'
          content_type: 'page'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        content_types:
          page: PageMapper
        destination: 'contentful/spaces/'
    - contributors:
        space: ENV_CONTENTFUL_EDB_SPACE_ID
        access_token: ENV_CONTENTFUL_EDB_ACCESS_TOKEN
        cda_query:
          locale: '*'
          content_type: 'contributor'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.pages.page'
    template: 'page'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.pages.page'
    template: 'page-fr'
    name: 'slug'
    dir: '/fr'
  - data: 'contentful.spaces.pages.page'
    template: 'page-hi'
    name: 'slug'
    dir: '/hi'
  - data: 'covid19.questions-en'
    template: 'entry'
    name: 'Question'
    dir: '/questions'
  - data: 'covid19.questions-fr'
    template: 'entry-fr'
    name: 'Question'
    dir: '/fr/questions'
    filter: 'Item status'
    filter_condition: record['Item status'] == 'Published'
  - data: 'covid19.questions-hi'
    template: 'entry-hi'
    name: 'id'
    dir: '/hi/questions'
    filter: 'Item status'
    filter_condition: record['Item status'] == 'Published'
  - data: 'covid19.glossary-en'
    template: 'term'
    name: 'Term'
    dir: '/glossary'


# Algolia search
algolia:
  application_id: XVQE72Q0TQ
  index_name: covid19
  search_only_api_key: d031b4f0809f3999da155451bffba6db
  nodes_to_index: 'p'
  files_to_exclude:
    - fr/index.html
    - hi/index.html
    - hi/**/index.html
    - about/index.html
    - fr/about/index.html
    - hi/about/index.html
    - glossary.html
    - fr/glossary.html
    - hi/glossary.html
    - meet-our-experts/index.html
    - hi/meet-our-experts/index.html
    - fr/meet-our-experts/index.html
    - ask-a-question/index.html
    - hi/ask-a-question/index.html
    - fr/ask-a-question/index.html
    - thanks/index.html
    - fr/thanks/index.html
    - hi/thanks/index.html
    - /questions/what-does-the-scientific-literature-say-about-using-hydroxychloroquine-to-prevent-treat-or-cure-covid-19/index.html
    - /questions/what-do-we-know-so-far-about-airborne-transmission-and-how-does-it-differ-from-respiratory-droplet-transmission/index.html
    - /questions/what-are-the-many-benefits-of-testing/index.html
    - /questions/why-are-brazils-cases-surging-right-now/index.html
    - /questions/what-do-we-know-so-far-about-dexamethasone-as-a-potential-treatment-for-covid-19/index.html
    - /questions/are-any-of-the-following-foods-or-drinks-alone-or-in-combination-with-other-effective-in-treating-or-curing-covid-19-turmeric-lemon-pineapple-onion-blackseed-oil-honey-garlic-tea-ginger-zinc-or-selenium/index.html
    - /questions/can-covid-19-be-transmitted-by-a-person-who-shows-no-symptoms/index.html
    - /questions/what-do-we-know-so-far-about-covid-19-losing-its-potency/index.html
    - /questions/why-are-we-repurposing-old-drugs-to-fight-new-diseases-and-what-might-be-the-implications-for-covid-19/index.html
    - /questions/are-there-ayurveda-cures-for-covid-19/index.html
    - /questions/how-are-migrant-laborers-in-india-being-impacted-by-the-covid-19-pandemic/index.html
    - /questions/is-there-any-relationship-between-the-use-of-antibiotics-and-treatment-of-covid-19/index.html
    - /fr/questions/quel-est-le-lien-entre-lutilisation-des-antibiotiques-et-le-traitement-du-covid-19-/index.html
    - /fr/questions/que-dit-la-science-sur-lutilisation-de-lhydroxychloroquine-pour-prevenir-traiter-ou-guerir-le-covid-19-/index.html
    - /fr/questions/le-covid-19-peut-il-etre-transmis-par-une-personne-qui-ne-presente-aucun-symptome-/index.html
    - /fr/questions/le-port-de-gants-freine-t-il-la-propagation-de-covid-19-/index.html
    - /fr/questions/que-dit-la-science-sur-lexposition-au-soleil-et-le-covid-19/index.html
    - /fr/questions/la-vaccination-au-bcg-protege-t-elle-contre-la-covid-19-/index.html

# Glossary
algolia:
  application_id: XVQE72Q0TQ
  index_name: covid19_glossary
  search_only_api_key: d031b4f0809f3999da155451bffba6db
  nodes_to_index: 'h4, p'
  files_to_exclude:
    - /index.html
    - /fr/index.html
    - /hi/index.html
    - /hi/**/index.html
    - /about/index.html
    - /fr/about/index.html
    - /hi/about/index.html
    - /questions/**/index.html
    - /fr/questions/**/index.html
    - /hi/questions/**/index.html
    - /meet-our-experts/
    - /meet-our-experts/index.html
    - /hi/meet-our-experts/index.html
    - /fr/meet-our-experts/index.html
    - /ask-a-question/
    - /ask-a-question/index.html
    - /hi/ask-a-question/index.html
    - /fr/ask-a-question/index.html
    - /thanks/index.html
    - /fr/thanks/index.html
    - /hi/thanks/index.html


# Airtable Fetch Configuration
airtable:
  api_key: key3GwTpP3iINPkP1
  tables:
    - name: 'airtable'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Expert Database (English)'
          view: 'COVID-19 Expert Database (English)'
          target: 'questions-en'
    - name: 'glossary'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Glossary (English)'
          view: 'Glossary (English)'
          target: 'glossary-en'
    - name: 'airtable'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Expert Database (French)'
          view: 'COVID-19 Expert Database (French)'
          target: 'questions-fr'
    - name: 'glossary'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Glossary (French)'
          view: 'Glossary (French)'
          target: 'glossary-fr'
    - name: 'airtable'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Expert Database (Hindi)'
          view: 'COVID-19 Expert Database (Hindi)'
          target: 'questions-hi' 
    - name: 'glossary'
      app_id: appKBFbOCN23iz8eF
      target: 'covid19'
      sheets:
        - name: 'Glossary (Hindi)'
          view: 'Glossary (Hindi)'
          target: 'glossary-hi'   
