# Generate glossary pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'covid19.glossary-en'
    template: 'term'
    name: 'id'
    dir: '/glossary'
  - data: 'covid19.glossary-fr'
    template: 'term'
    name: 'id'
    dir: '/fr/glossary'
  - data: 'covid19.glossary-hi'
    template: 'term'
    name: 'id'
    dir: '/hi/glossary'
  - data: 'covid19.glossary-te'
    template: 'term'
    name: 'id'
    dir: '/te/glossary'
  - data: 'covid19.glossary-es'
    template: 'term'
    name: 'id'
    dir: '/es/glossary'
  - data: 'covid19.glossary-pt'
    template: 'term'
    name: 'id'
    dir: '/pt/glossary'

# Glossary
algolia:
  application_id: ENV_ALGOLIA_APPLICATION_ID
  index_name: ENV_ALGOLIA_INDEX_NAME_GLOSSARY
  search_only_api_key: d031b4f0809f3999da155451bffba6db
  nodes_to_index: 'h4, p'
  files_to_exclude:
    - /index.html
    - /fr/index.html
    - /hi/index.html
    - /te/index.html
    - /es/index.html
    - /pt/index.html
    - /bn/index.html
    - /ar/index.html
    - /about/index.html
    - /**/about/index.html
    - /questions/**/index.html
    - /**/questions/**/index.html
    - /meet-our-experts/
    - /meet-our-experts/index.html
    - /**/meet-our-experts/index.html
    - /ask-a-question/
    - /ask-a-question/index.html
    - /**/ask-a-question/index.html
    - /thanks/index.html
    - /**/thanks/index.html