[[redirects]]
  from = "https://health-desk.org"
  to = "https://health-desk.org/vaccines"
  status = 200

[[redirects]]
  from = "https://health-desk.org/*"
  to = "https://health-desk.org/vaccines"
  status = 200